steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/angular-chat", "."]

# push the container image to Container Registry
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/angular-chat"]

# Deploy container image to Cloud Run
- name: "gcr.io/cloud-builders/gcloud"
  args: [ "beta", 
        "run", 
        "deploy", 
        "--allow-unauthenticated", 
        "$PROJECT_ID", 
        "--image", 
        "gcr.io/$PROJECT_ID/angular-chat",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--memory",
        "128Mi" ]
images:
- "gcr.io/$PROJECT_ID/angular-chat"